#!/usr/bin/env python3
"""Builds supplemental_data.docx: full source-data tables (Data S1-S8) for the
project1 S100A8+ macrophage deconvolution manuscript, each with a description of
what it contains, how it was generated, and what it is useful for."""

import os
import csv
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

REPO = os.path.join(os.path.dirname(__file__), "..")
RESULTS = os.path.join(REPO, "results")
EXT_RESULTS = os.path.join(REPO, "external_validation", "results")
FIG = os.path.join(REPO, "figures")
EXT_FIG = os.path.join(REPO, "external_validation", "figures")
OUT_PATH = os.path.join(os.path.dirname(__file__), "supplemental_data.docx")

doc = Document()

# ---------------------------------------------------------------- styles ---
section = doc.sections[0]
section.orientation = WD_ORIENT.LANDSCAPE
section.page_width, section.page_height = Inches(11), Inches(8.5)
for m in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
    setattr(section, m, Inches(0.7))

normal = doc.styles["Normal"]
normal.font.name = "Times New Roman"
normal.font.size = Pt(11)
normal.paragraph_format.space_after = Pt(8)
normal.paragraph_format.line_spacing = 1.3
rpr = normal.element.get_or_add_rPr()
rFonts = rpr.find(qn("w:rFonts"))
if rFonts is None:
    rFonts = OxmlElement("w:rFonts")
    rpr.append(rFonts)
rFonts.set(qn("w:eastAsia"), "Times New Roman")

for lvl, size, bold in [(1, 15, True), (2, 13, True)]:
    style = doc.styles[f"Heading {lvl}"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(size)
    style.font.bold = bold
    style.font.color.rgb = RGBColor(0, 0, 0)
    style.paragraph_format.space_before = Pt(14)
    style.paragraph_format.space_after = Pt(6)


def add_para(text, size=11, bold=False, italic=False, space_after=8):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    r.font.size = Pt(size)
    p.paragraph_format.space_after = Pt(space_after)
    return p


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def fmt(val, decimals=None):
    if val is None or val == "":
        return ""
    try:
        f = float(val)
    except ValueError:
        return val.strip('"')
    if decimals is None:
        return str(val)
    if abs(f) < 0.001 and f != 0:
        return f"{f:.2e}"
    return f"{f:.{decimals}f}"


def make_table(headers, rows, font_size=8, col_widths=None):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        run = hdr[i].paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(font_size)
    for row in rows:
        cells = table.add_row().cells
        for i, val in enumerate(row):
            run = cells[i].paragraphs[0].add_run(str(val))
            run.font.size = Pt(font_size)
    if col_widths:
        for row in table.rows:
            for i, w in enumerate(col_widths):
                row.cells[i].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)
    return table


def data_heading(num, title):
    doc.add_heading(f"Data S{num}. {title}", level=2)


def source_line(path, script):
    p = doc.add_paragraph()
    r = p.add_run(f"Source file: {path}   |   Generated by: {script}")
    r.italic = True
    r.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(10)


def fig_heading(num, title):
    doc.add_heading(f"Figure S{num}. {title}", level=2)


def add_figure(fig_root, png_name, width_in, description, script):
    doc.add_picture(os.path.join(fig_root, png_name), width=Inches(width_in))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_para(description)
    p = doc.add_paragraph()
    r = p.add_run(f"Source file: {os.path.relpath(fig_root, REPO)}/{png_name}   |   Generated by: {script}")
    r.italic = True
    r.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(14)


# ============================================================ TITLE PAGE ===
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Supplemental Data")
r.bold = True
r.font.size = Pt(18)
title.paragraph_format.space_after = Pt(6)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = subtitle.add_run(
    "Cross-Validated Deconvolution Identifies General Hepatic Macrophage "
    "Burden, Not an S100A8-Hi Subset, as the Lipogenic-Gene Correlate in "
    "Mouse MASLD"
)
r.italic = True
r.font.size = Pt(13)
subtitle.paragraph_format.space_after = Pt(20)

intro = doc.add_paragraph()
intro.add_run(
    "This document provides full source-data tables (Data S1-S17) and figures "
    "(Figure S1-S9) supporting the statistical claims in the main manuscript, "
    "including its follow-up analysis (Section 3.6) of the origin, transcriptional "
    "trigger, and fate of the S100A8-hi macrophage population. Each entry states "
    "what it contains, how it was generated, and what question it lets the reader "
    "check independently. Full analysis code is at "
    "https://github.com/bioinform25/project1; the exact source CSV/PNG for each "
    "item is named below it. Numeric values are rounded for display; unrounded "
    "values are in the source CSVs."
)
doc.add_page_break()

# ================================================================ DATA S1 ==
data_heading(1, "Full axis-1 (WT vs Bcl2TG, HFD) deconvolution statistics — all 12 cell types")
add_para(
    "Referenced in: Results 3.2 (\"Four additional cell types reached BH q = 0.024...\"), "
    "Figure 2. Every cell type's Wilcoxon/Welch comparison, Cohen's d, 95% CI and "
    "BH-adjusted q-values for the axis-1 validation cohort (n = 5 WT vs n = 5 Bcl2TG, "
    "HFD) are reported here, not only the two highlighted in the main text (Macrophage_"
    "Kupffer, S100A8hi_macrophage). Generated by scripts/11_statistical_rigor_addendum.R. "
    "Useful for: checking whether a specific cell type not discussed in the main text "
    "reached significance, and for re-deriving Figure 2's underlying numbers."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_axis1_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        f"[{fmt(d['ci95_lo'], 2)}, {fmt(d['ci95_hi'], 2)}]",
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "n (WT vs TG)", "Mean WT", "Mean TG", "Cohen's d", "95% CI (mean diff)",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_axis1_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")

# ================================================================ DATA S2 ==
data_heading(2, "Full axis-2 (WT vs MKO) deconvolution statistics — all 12 cell types x 2 diets")
add_para(
    "Referenced in: Results 3.3, Figure 3. Every cell type's WT-vs-MKO comparison in "
    "both chow and HFD, including the two cell types with the largest nominal, "
    "BH-uncorrected effects (Neutrophil, Mast_cell) highlighted in the main text. "
    "Generated by scripts/11_statistical_rigor_addendum.R. Useful for: confirming that "
    "no cell type reached BH q < 0.05 in either diet (Results 3.3), and for identifying "
    "which cell types had the largest (even if non-significant) effect sizes as leads "
    "for a follow-up, adequately powered study."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_MKO_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["diet"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "Diet", "n (MKO vs WT)", "Mean MKO", "Mean WT", "Cohen's d",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_MKO_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")
doc.add_page_break()

# ================================================================ DATA S3 ==
data_heading(3, "Full lipogenic-gene correlation results — all 30 tests")
add_para(
    "Referenced in: Results 3.4, Figure 4C. Spearman correlations between "
    "Macrophage_Kupffer / S100A8hi_macrophage deconvolution scores and five lipogenic "
    "genes (Cd36, Fasn, Plin2, Pparg, Scd1), computed in three overlapping sample "
    "subsets (all 19 HFD samples, axis-1 HFD only, axis-2 HFD only). Generated by "
    "scripts/11_statistical_rigor_addendum.R. Useful for: seeing the BH correction "
    "applied across all 30 tests at once (the source of the q-values quoted in the "
    "main text), and for checking genes/subsets not singled out in Figure 4."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_lipid_correlation_BH.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["gene"], d["subset"], d["n"],
        fmt(d["r"], 2), fmt(d["p_value"], 3),
        fmt(d["p_BH_within_subset"], 3), fmt(d["p_BH_all30"], 3),
    ])
make_table(
    ["Cell type", "Gene", "Subset", "n", "Spearman r", "p-value",
     "BH-q (within subset)", "BH-q (all 30 tests)"],
    out_rows, font_size=8,
)
source_line("results/11_lipid_correlation_BH.csv", "scripts/11_statistical_rigor_addendum.R")
doc.add_page_break()

# ================================================================ DATA S4 ==
data_heading(4, "GSE156057: marker-gene expression by cluster — all 40 clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5A. Percent of cells expressing "
    "each of 17 lineage/identity marker genes, for every one of the 40 clusters "
    "identified in the reclustered GSE156057 (CD45+-sorted) dataset — not only the 6 "
    "clusters (3 candidate S100A8-hi, 1 neutrophil, 2 Kupffer) shown in Figure 5A. "
    "Generated by external_validation/scripts/03_gse156057_qc_cluster.R. Useful for: "
    "independently checking the S100A8-hi / neutrophil / Kupffer classification "
    "criteria (Methods 2.7) against every cluster, not just the ones we selected as "
    "examples."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=7)
source_line("external_validation/results/gse156057_pct_expr_by_cluster.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S5 ==
data_heading(5, "GSE156057: top 5 differential marker genes per cluster (all 40 clusters)")
add_para(
    "Referenced in: Results 3.5, Methods 2.7. The five most significantly "
    "up-regulated marker genes (Seurat FindAllMarkers, Wilcoxon rank-sum, "
    "avg_log2FC-ranked) for each of the 40 GSE156057 clusters, condensed from the "
    "complete differential-expression table. Generated by external_validation/"
    "scripts/03_gse156057_qc_cluster.R. Useful for: independently naming/annotating "
    "any cluster referenced by number in Data S4 or Figure 5, without needing to "
    "open the full marker table. The complete, unabbreviated result (24,030 gene x "
    "cluster comparisons, all with p-values) is provided separately as "
    "external_validation/results/gse156057_cluster_markers.csv in the code "
    "repository (too large to reproduce in full here)."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_cluster_top5.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cluster"].strip('"'), d["gene"].strip('"'),
        fmt(d["avg_log2FC"], 2), fmt(d["pct.1"], 2), fmt(d["pct.2"], 2),
        fmt(d["p_val"], 3), fmt(d["p_val_adj"], 3),
    ])
make_table(
    ["Cluster", "Gene", "avg log2FC", "% expr. (in cluster)", "% expr. (other clusters)",
     "p-value", "BH-adj p-value"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_cluster_top5.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S6 ==
data_heading(6, "GSE156057: S100A8-hi / Kupffer / Neutrophil proportions by diet and timepoint")
add_para(
    "Referenced in: Results 3.5, Figure 5B. Per-sample cell counts and proportions "
    "(of all CD45+ cells sequenced in that sample) for the combined S100A8-hi "
    "macrophage clusters, the Kupffer clusters, and the neutrophil cluster, across "
    "all 6 GSE156057 samples (standard diet [SD] / western diet [WD] x 12/24/36 "
    "weeks). \"Other\" comprises all remaining clusters (T/B/NK/DC/etc.). Generated "
    "by external_validation/scripts/04_gse156057_proportions.R. Useful for: the "
    "exact per-sample numbers behind the WD/SD ratios quoted in Results 3.5 (1.45 "
    "at 12 weeks, 1.21 at 24 weeks, 0.81 at 36 weeks) and behind Figure 5B."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_S100A8hi_proportions.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["sample"].strip('"'), d["diet"].strip('"'), d["timepoint"].strip('"'),
        d["cell_class"].strip('"'), d["n"], d["total"],
        f"{float(d['proportion'])*100:.2f}%",
    ])
make_table(
    ["Sample", "Diet", "Timepoint", "Cell class", "n cells", "Total CD45+ cells", "Proportion"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_S100A8hi_proportions.csv",
            "external_validation/scripts/04_gse156057_proportions.R")
doc.add_page_break()

# ================================================================ DATA S7 ==
data_heading(7, "GSE166504: marker-gene expression by cluster — all 18 myeloid clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5C. Percent of cells expressing "
    "12 lineage/identity marker genes for every one of the 18 clusters identified "
    "within the reclustered myeloid compartment of GSE166504 (whole-liver, true "
    "biological replicates). Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: the full data behind Figure 5C's "
    "claim that S100a8 positivity forms a gradient rather than isolating a discrete "
    "cluster among monocyte/macrophage-lineage populations."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=8)
source_line("external_validation/results/gse166504_pct_expr_by_cluster.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ================================================================ DATA S8 ==
data_heading(8, "GSE166504: cluster identity cross-tabulation vs author-provided cell-type labels")
add_para(
    "Referenced in: Methods 2.7, Results 3.5. Number of cells per re-clustering "
    "cluster (rows) assigned to each of the original authors' three coarse "
    "myeloid cell-type labels (columns: Kupffer cells, Monocyte/Monocyte-derived "
    "macrophage, Neutrophils), used to determine the \"dominant cell-type label\" "
    "coloring in Figure 5C. Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: checking cluster purity — e.g., "
    "whether a given cluster is a clean match to one author label or a mixture."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_cluster_vs_authorlabel.csv"))
out_rows = []
for row in rows:
    out_rows.append([row[0].strip('"')] + row[1:])
make_table(["Cluster"] + headers[1:], out_rows, font_size=9)
source_line("external_validation/results/gse166504_cluster_vs_authorlabel.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ================================================================ DATA S9 ==
data_heading(9, "Monocyte-recruitment vs. resident-Kupffer marker panel, by refined origin group")
add_para(
    "Referenced in: Methods 2.2, Results 3.1, Section 4 (Discussion). Percent of "
    "cells expressing each of 12 literature-established monocyte-recruitment "
    "(Ly6c2, Ccr2, Sell, Plac8, Chil3), resident-Kupffer (Clec4f, Timd4, Vsig4, "
    "Cd5l, Marco) and lipid-associated-macrophage (Trem2, Gpnmb) marker genes, "
    "for S100A8hi_macrophage, Neutrophil, and the Macrophage_Kupffer compartment "
    "split into its two transcriptionally distinct constituent subsets: "
    "Kupffer_resident (original clusters 18+10, Clec4f/Vsig4/Cd5l-high) and "
    "Macrophage_MoMF_LAM (original clusters 5+11, Ccr2/Plac8-high, partially "
    "Trem2/Gpnmb-high). This split was motivated by an initial sanity check "
    "(during follow-up analysis) showing that a single merged Macrophage_Kupffer "
    "group scored unexpectedly high on monocyte-recruitment markers -- "
    "investigating why revealed that two of its four constituent subclusters "
    "(67% of its cells) carry a Ccr2-high monocyte-derived signature rather than "
    "a resident-Kupffer one. Generated by scripts/13_origin_signature_scoring.R. "
    "Useful for: verifying the Section 3.1/Section 4 claim that S100A8hi_"
    "macrophage lacks the classical Ccr2-dependent monocyte-recruitment "
    "signature (unlike the Ccr2-high subset of Macrophage_Kupffer), and for "
    "seeing the full 12-gene panel behind that conclusion rather than the two "
    "or three genes highlighted in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "13_origin_marker_panel_percluster.csv"))
pct_genes = ["Ly6c2", "Ccr2", "Sell", "Plac8", "Chil3", "Clec4f", "Timd4", "Vsig4", "Cd5l", "Marco", "Trem2", "Gpnmb"]
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d[gene + '_pct']) * 100:.1f}%" for gene in pct_genes])
make_table(["Origin group"] + [f"{g} (% pos.)" for g in pct_genes], out_rows, font_size=8)
source_line("results/13_origin_marker_panel_percluster.csv", "scripts/13_origin_signature_scoring.R")
doc.add_page_break()

# =============================================================== DATA S10 ==
data_heading(10, "Origin composite-score statistics, primary reference (secondary evidence to Data S9)")
add_para(
    "Referenced in: Section 4 (Discussion). Seurat AddModuleScore composite statistics "
    "(Wilcoxon/Welch, Cohen's d, BH-corrected within this 8-test family) for the "
    "monocyte-recruitment and resident-Kupffer composite scores across all pairwise "
    "comparisons of the four refined origin groups. Reported as secondary evidence "
    "alongside Data S9's per-gene panel because composite module scores can be skewed "
    "by individual non-specific genes within a signature (observed during this analysis: "
    "Ly6c2/Sell/Chil3 are not monocyte-lineage-specific in this dataset, being highly "
    "expressed in Neutrophil too -- see Data S9). Generated by "
    "scripts/13_origin_signature_scoring.R. Useful for: the full statistical backing "
    "for every pairwise composite-score comparison mentioned in the text."
)
headers, rows = read_csv(os.path.join(RESULTS, "13_origin_scores_primary_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("results/13_origin_scores_primary_stats.csv", "scripts/13_origin_signature_scoring.R")

# =============================================================== DATA S11 ==
data_heading(11, "Origin-signature score comparisons, GSE156057 (cross-dataset replication attempt)")
add_para(
    "Referenced in: Section 4 (Discussion). Same composite-score comparison as Data S10 "
    "(S100A8hi_macrophage vs. Kupffer vs. Neutrophil), repeated in the independent "
    "GSE156057 dataset. Unlike the primary reference, S100A8hi_macrophage here scores "
    "higher, not lower, on the monocyte-recruitment composite than the (single, "
    "unsplit) Kupffer cluster group -- per-gene inspection (Data S4) showed this "
    "reflects heterogeneity within GSE156057's own 3-cluster S100A8hi candidate set "
    "(Ccr2 ranges 2.6%-74.7% across the three clusters), mirroring the same "
    "within-group heterogeneity phenomenon documented in Data S9 for the primary "
    "reference's Macrophage_Kupffer label, rather than a clean replication or "
    "contradiction. Generated by "
    "external_validation/scripts/06_origin_signature_scoring.R. Useful for: seeing "
    "why composite scores should not be over-interpreted at this cluster resolution "
    "without the underlying per-gene breakdown."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse156057_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("external_validation/results/06_origin_scores_gse156057_stats.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")
doc.add_page_break()

# =============================================================== DATA S12 ==
data_heading(12, "Origin-signature score vs. S100a8 expression, GSE166504 (cluster-level correlation)")
add_para(
    "Referenced in: Section 4 (Discussion). GSE166504 has no discrete S100A8hi cluster "
    "(only a continuous gradient, Results 3.5), so origin scores are tested here as a "
    "cluster-level correlation instead of a group comparison: across the 18 myeloid "
    "clusters, does average S100a8 expression track more closely with the "
    "monocyte-recruitment score or the resident-Kupffer score? Resident score showed a "
    "borderline negative correlation (Spearman rho = -0.47, p = 0.05, i.e. higher S100a8 "
    "weakly tracks away from resident identity); monocyte-recruitment score did not "
    "(rho = 0.21, p = 0.41). Generated by "
    "external_validation/scripts/06_origin_signature_scoring.R. Useful for: the full "
    "per-cluster values behind this correlation, and the correlation statistics table."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse166504_correlation.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["score"].strip('"'), d["n_clusters"], fmt(d["spearman_rho"], 3), fmt(d["p_value"], 3)])
make_table(["Score", "n clusters", "Spearman rho", "p-value"], out_rows, font_size=9)
source_line("external_validation/results/06_origin_scores_gse166504_correlation.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")

headers2, rows2 = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse166504_cluster_avg.csv"))
out_rows2 = []
for row in rows2:
    d = dict(zip(headers2, row))
    out_rows2.append([d["seurat_clusters"].strip('"'), fmt(d["S100a8_expr"], 3),
                       fmt(d["MonocyteScore"], 3), fmt(d["ResidentScore"], 3), d["n_cells"]])
make_table(["Cluster", "S100a8 avg. expr.", "Monocyte score (avg.)", "Resident score (avg.)", "n cells"],
           out_rows2, font_size=9)
source_line("external_validation/results/06_origin_scores_gse166504_cluster_avg.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")
doc.add_page_break()

# =============================================================== DATA S13 ==
data_heading(13, "TF mRNA vs. S100a9 expression / S100A8hi_macrophage score, bulk RNA-seq (all 34 samples)")
add_para(
    "Referenced in: Results 3.6, Methods 2.2/2.3. The original paper proposed, but did "
    "not test, that C/EBP or AP-1 family transcription factors regulate S100A8 "
    "induction. Formal TF activity inference (decoupleR + CollecTRI/DoRothEA) was "
    "attempted but failed in this environment due to a currently open upstream bug in "
    "OmnipathR's organism database (GitHub saezlab/OmnipathR issues #128, #121 -- "
    "reproduced even after updating to the latest GitHub development version, and "
    "affecting other users independently of this machine). As a transparent fallback, "
    "TF mRNA expression itself was used as a proxy (AP-1 genes are classic "
    "immediate-early genes whose own expression is a standard activation readout). "
    "Spearman correlation of each TF gene's bulk expression against S100a9 expression "
    "and against the deconvolved S100A8hi_macrophage score, in all 34 samples and in "
    "the 19-sample HFD-only subset, BH-corrected within each subset x target family "
    "(9 tests). No TF reached BH q < 0.05 against either target in either subset. "
    "Generated by scripts/14_tf_activity_inference.R. Useful for: the full correlation "
    "table behind the Results 3.6 null finding, including genes/subsets not singled "
    "out in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_bulk_correlation.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["tf_family"].strip('"'), d["tf_gene"].strip('"'), d["target"].strip('"'), d["subset"].strip('"'),
        fmt(d["r"], 3), fmt(d["p_value"], 3), d["n"], fmt(d["p_BH"], 3),
    ])
make_table(["TF family", "TF gene", "Target", "Subset", "Spearman r", "p-value", "n", "BH-q"],
           out_rows, font_size=8)
source_line("results/14_tf_bulk_correlation.csv", "scripts/14_tf_activity_inference.R")
doc.add_page_break()

# =============================================================== DATA S14 ==
data_heading(14, "C/EBP and AP-1 family TF mRNA panel by refined origin group, primary scRNA reference")
add_para(
    "Referenced in: Results 3.6. Percent of cells expressing (and average expression "
    "of) each of 9 C/EBP-family (Cebpa, Cebpb, Cebpd) and AP-1-family (Fos, Fosb, Jun, "
    "Junb, Jund, Atf3) transcription factor genes, across the same four refined origin "
    "groups used in Data S9. Notably, Cebpa -- the C/EBP paralog most implicated in "
    "myeloid inflammatory gene induction in the literature -- is lowest in "
    "S100A8hi_macrophage (4.4%) and highest in Macrophage_MoMF_LAM (51.1%), the "
    "opposite of what a simple 'C/EBP drives S100A8hi identity' model would predict. "
    "Generated by scripts/14_tf_activity_inference.R. Useful for: checking any "
    "individual TF gene's expression pattern beyond the two (Cebpa, Ap1Score) "
    "highlighted in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_scrna_percluster.csv"))
tf_genes = ["Cebpa", "Cebpb", "Cebpd", "Fos", "Fosb", "Jun", "Junb", "Jund", "Atf3"]
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d[gene + '_pct']) * 100:.1f}%" for gene in tf_genes])
make_table(["Origin group"] + [f"{g} (% pos.)" for g in tf_genes], out_rows, font_size=8)
source_line("results/14_tf_scrna_percluster.csv", "scripts/14_tf_activity_inference.R")

# =============================================================== DATA S15 ==
data_heading(15, "C/EBP-score and AP1-score composite comparisons, primary scRNA reference")
add_para(
    "Referenced in: Results 3.6. Composite AddModuleScore statistics (same design as "
    "Data S10) for the C/EBP-family and AP-1-family gene sets, across pairwise "
    "comparisons of S100A8hi_macrophage against the other three refined origin groups. "
    "S100A8hi_macrophage's Ap1Score does not differ from Macrophage_MoMF_LAM's "
    "(Cohen's d = 0.02, Wilcoxon p = 0.74), despite differing significantly from both "
    "Kupffer_resident and Neutrophil -- i.e. AP-1 activity alone does not distinguish "
    "S100A8hi_macrophage from the Ccr2-high MoMF/LAM population the way Ccr2 itself "
    "does (Data S9). Generated by scripts/14_tf_activity_inference.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_scrna_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("results/14_tf_scrna_stats.csv", "scripts/14_tf_activity_inference.R")
doc.add_page_break()

# =============================================================== DATA S16 ==
data_heading(16, "S100A8hi_macrophage vs. Kupffer proportion trend over time, GSE156057")
add_para(
    "Referenced in: Results 3.6. Linear regression slope of cell-class proportion "
    "against timepoint (12/24/36 weeks), fit separately for S100A8hi_macrophage and "
    "Kupffer, within each diet arm (SD, WD; n = 3 timepoints per diet, one sample "
    "each -- severely underpowered, direction only, not a statistical claim). Under "
    "WD, S100A8hi_macrophage's slope is negative (-0.0010/week) while Kupffer's is "
    "positive (+0.0003/week) -- directionally consistent with a maturation model "
    "(S100A8hi declining as a Kupffer-like population accumulates) but neither slope "
    "is statistically distinguishable from zero at this sample size (p = 0.17, "
    "p = 0.60). Generated by scripts/15_fate_trajectory.R. Useful for: the exact "
    "slope/p-value numbers behind the Results 3.6 statement that this trend is "
    "directionally suggestive but not statistically resolvable."
)
headers, rows = read_csv(os.path.join(RESULTS, "15_fate_compositional_trend.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["cell_class"].strip('"'), d["diet"].strip('"'), d["n"], fmt(d["slope"], 5), fmt(d["p_value"], 3)])
make_table(["Cell class", "Diet", "n timepoints", "Slope (proportion/week)", "p-value"], out_rows, font_size=9)
source_line("results/15_fate_compositional_trend.csv", "scripts/15_fate_trajectory.R")

# =============================================================== DATA S17 ==
data_heading(17, "PCA-space nearest-neighbor composition by refined origin group (transcriptional continuity)")
add_para(
    "Referenced in: Results 3.6, Section 4 (Discussion). For each cell in the four "
    "refined origin groups, the origin-group identity of its k = 30 nearest neighbors "
    "in a PCA space computed from just these four groups (to avoid dilution by "
    "unrelated cell types), averaged per group. High on-diagonal values indicate "
    "discrete, well-separated states; off-diagonal 'leakage' indicates a transcriptional "
    "continuum. S100A8hi_macrophage is 96.2% self-neighboring (1.6% leakage into "
    "Macrophage_MoMF_LAM, 2.0% into Kupffer_resident), while Kupffer_resident and "
    "Macrophage_MoMF_LAM leak into each other at 7.3%/2.6% -- consistent with the "
    "established monocyte-to-Kupffer differentiation continuum (Guilliams et al. 2022; "
    "Scott et al. 2016; Bonnardel et al. 2019 -- see main-text references 11-13) and "
    "arguing against S100A8hi_macrophage being an early point on that same trajectory. "
    "Generated by scripts/15_fate_trajectory.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "15_fate_neighbor_purity.csv"))
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d['pct_neighbors_' + g2]) * 100:.1f}%" for g2 in group_order] + [d["n_cells"]])
make_table(["Own group"] + [f"% neighbors: {g}" for g in group_order] + ["n cells"], out_rows, font_size=8)
source_line("results/15_fate_neighbor_purity.csv", "scripts/15_fate_trajectory.R")
doc.add_page_break()

# ======================================================= SUPPLEMENTAL FIGURES ==
title2 = doc.add_paragraph()
title2.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title2.add_run("Supplemental Figures")
r.bold = True
r.font.size = Pt(16)
title2.paragraph_format.space_after = Pt(18)

fig_heading(1, "Origin/identity marker dot plot, primary scRNA reference")
add_figure(FIG, "13_origin_marker_dotplot.png", 7.5,
           "Dot plot of the 12-gene origin/identity marker panel (Data S9) across the four "
           "refined origin groups (S100A8hi_macrophage, Kupffer_resident, Macrophage_MoMF_LAM, "
           "Neutrophil), primary scRNA reference. Referenced in Results 3.1, Section 4.",
           "scripts/13_origin_signature_scoring.R")

fig_heading(2, "Monocyte-recruitment and resident-Kupffer composite scores by origin group, primary reference")
add_figure(FIG, "13_origin_scores_primary.png", 9.5,
           "Violin/boxplots of the two composite module scores (Data S10) across the four "
           "refined origin groups. Referenced in Section 4.",
           "scripts/13_origin_signature_scoring.R")

fig_heading(3, "Origin-signature composite scores by cell class, GSE156057")
add_figure(EXT_FIG, "06_origin_scores_gse156057.png", 9.5,
           "Same composite scores as Fig S2, computed in the independent GSE156057 dataset "
           "(Data S11). Referenced in Section 4.",
           "external_validation/scripts/06_origin_signature_scoring.R")

fig_heading(4, "Cluster-average S100a8 expression vs. origin scores, GSE166504")
add_figure(EXT_FIG, "06_origin_scores_gse166504.png", 9.5,
           "Cluster-level scatter of average S100a8 expression against the monocyte-recruitment "
           "and resident-Kupffer composite scores, across all 18 myeloid clusters (Data S12). "
           "Referenced in Section 4.",
           "external_validation/scripts/06_origin_signature_scoring.R")

fig_heading(5, "TF mRNA vs. S100a9 expression, bulk RNA-seq (all 34 samples)")
add_figure(FIG, "14_tf_bulk_correlation.png", 9.5,
           "Scatter plots of each of 9 C/EBP- and AP-1-family TF genes' bulk expression against "
           "S100a9 expression, one panel per gene (Data S13). Referenced in Results 3.6.",
           "scripts/14_tf_activity_inference.R")

fig_heading(6, "C/EBP and AP-1 family TF mRNA dot plot by origin group, primary scRNA reference")
add_figure(FIG, "14_tf_scrna_dotplot.png", 7.5,
           "Dot plot of the 9-gene TF panel (Data S14) across the four refined origin groups. "
           "Referenced in Results 3.6.",
           "scripts/14_tf_activity_inference.R")

fig_heading(7, "S100A8hi_macrophage vs. Kupffer proportion over time, GSE156057")
add_figure(FIG, "15_fate_compositional_trend.png", 8,
           "Cell-class proportion vs. timepoint (12/24/36 weeks), by diet, for S100A8hi_macrophage "
           "and Kupffer (Data S16). Referenced in Results 3.6.",
           "scripts/15_fate_trajectory.R")

fig_heading(8, "Restricted UMAP of the four refined origin groups, primary scRNA reference")
add_figure(FIG, "15_fate_umap_origin.png", 6,
           "UMAP computed from only the four refined origin groups (S100A8hi_macrophage, "
           "Kupffer_resident, Macrophage_MoMF_LAM, Neutrophil), colored by group. Underlies the "
           "PCA-space nearest-neighbor analysis in Data S17. Referenced in Results 3.6, Section 4.",
           "scripts/15_fate_trajectory.R")

fig_heading(9, "Trem2/Gpnmb (LAM) module score on the restricted UMAP")
add_figure(FIG, "15_fate_umap_lamscore.png", 6,
           "Same UMAP embedding as Fig S8, colored by the Trem2/Gpnmb lipid-associated-macrophage "
           "module score, showing this signature concentrates in Macrophage_MoMF_LAM and is absent "
           "from S100A8hi_macrophage. Referenced in Results 3.1, Results 3.6.",
           "scripts/15_fate_trajectory.R")

print("Document complete.")
doc.save(OUT_PATH)
print(f"Saved to {OUT_PATH}")
