#!/usr/bin/env python3
"""Builds supplemental_data.docx: full source-data tables (Data S1-S8) for the
project1 S100A8+ macrophage deconvolution manuscript, each with a description of
what it contains, how it was generated, and what it is useful for."""

import os
import csv
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

REPO = os.path.join(os.path.dirname(__file__), "..")
RESULTS = os.path.join(REPO, "results")
EXT_RESULTS = os.path.join(REPO, "external_validation", "results")
OUT_PATH = os.path.join(os.path.dirname(__file__), "supplemental_data.docx")

doc = Document()

# ---------------------------------------------------------------- styles ---
section = doc.sections[0]
section.orientation = WD_ORIENT.LANDSCAPE
section.page_width, section.page_height = Inches(11), Inches(8.5)
for m in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
    setattr(section, m, Inches(0.7))

normal = doc.styles["Normal"]
normal.font.name = "Times New Roman"
normal.font.size = Pt(11)
normal.paragraph_format.space_after = Pt(8)
normal.paragraph_format.line_spacing = 1.3
rpr = normal.element.get_or_add_rPr()
rFonts = rpr.find(qn("w:rFonts"))
if rFonts is None:
    rFonts = OxmlElement("w:rFonts")
    rpr.append(rFonts)
rFonts.set(qn("w:eastAsia"), "Times New Roman")

for lvl, size, bold in [(1, 15, True), (2, 13, True)]:
    style = doc.styles[f"Heading {lvl}"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(size)
    style.font.bold = bold
    style.font.color.rgb = RGBColor(0, 0, 0)
    style.paragraph_format.space_before = Pt(14)
    style.paragraph_format.space_after = Pt(6)


def add_para(text, size=11, bold=False, italic=False, space_after=8):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    r.font.size = Pt(size)
    p.paragraph_format.space_after = Pt(space_after)
    return p


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def fmt(val, decimals=None):
    if val is None or val == "":
        return ""
    try:
        f = float(val)
    except ValueError:
        return val.strip('"')
    if decimals is None:
        return str(val)
    if abs(f) < 0.001 and f != 0:
        return f"{f:.2e}"
    return f"{f:.{decimals}f}"


def make_table(headers, rows, font_size=8, col_widths=None):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        run = hdr[i].paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(font_size)
    for row in rows:
        cells = table.add_row().cells
        for i, val in enumerate(row):
            run = cells[i].paragraphs[0].add_run(str(val))
            run.font.size = Pt(font_size)
    if col_widths:
        for row in table.rows:
            for i, w in enumerate(col_widths):
                row.cells[i].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)
    return table


def data_heading(num, title):
    doc.add_heading(f"Data S{num}. {title}", level=2)


def source_line(path, script):
    p = doc.add_paragraph()
    r = p.add_run(f"Source file: {path}   |   Generated by: {script}")
    r.italic = True
    r.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(10)


# ============================================================ TITLE PAGE ===
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Supplemental Data")
r.bold = True
r.font.size = Pt(18)
title.paragraph_format.space_after = Pt(6)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = subtitle.add_run(
    "Cross-Validated Deconvolution Identifies General Hepatic Macrophage "
    "Burden, Not an S100A8-Hi Subset, as the Lipogenic-Gene Correlate in "
    "Mouse MASLD"
)
r.italic = True
r.font.size = Pt(13)
subtitle.paragraph_format.space_after = Pt(20)

intro = doc.add_paragraph()
intro.add_run(
    "This document provides full source-data tables (Data S1-S8) supporting the "
    "statistical claims and figures in the main manuscript. Each entry states what "
    "the table contains, how it was generated, and what question it lets the reader "
    "check independently. Full analysis code is at "
    "https://github.com/bioinform25/project1; the exact source CSV for each table "
    "is named below it. Numeric values are rounded for display; unrounded values "
    "are in the source CSVs."
)
doc.add_page_break()

# ================================================================ DATA S1 ==
data_heading(1, "Full axis-1 (WT vs Bcl2TG, HFD) deconvolution statistics — all 12 cell types")
add_para(
    "Referenced in: Results 3.2 (\"Four additional cell types reached BH q = 0.024...\"), "
    "Figure 2. Every cell type's Wilcoxon/Welch comparison, Cohen's d, 95% CI and "
    "BH-adjusted q-values for the axis-1 validation cohort (n = 5 WT vs n = 5 Bcl2TG, "
    "HFD) are reported here, not only the two highlighted in the main text (Macrophage_"
    "Kupffer, S100A8hi_macrophage). Generated by scripts/11_statistical_rigor_addendum.R. "
    "Useful for: checking whether a specific cell type not discussed in the main text "
    "reached significance, and for re-deriving Figure 2's underlying numbers."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_axis1_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        f"[{fmt(d['ci95_lo'], 2)}, {fmt(d['ci95_hi'], 2)}]",
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "n (WT vs TG)", "Mean WT", "Mean TG", "Cohen's d", "95% CI (mean diff)",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_axis1_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")

# ================================================================ DATA S2 ==
data_heading(2, "Full axis-2 (WT vs MKO) deconvolution statistics — all 12 cell types x 2 diets")
add_para(
    "Referenced in: Results 3.3, Figure 3. Every cell type's WT-vs-MKO comparison in "
    "both chow and HFD, including the two cell types with the largest nominal, "
    "BH-uncorrected effects (Neutrophil, Mast_cell) highlighted in the main text. "
    "Generated by scripts/11_statistical_rigor_addendum.R. Useful for: confirming that "
    "no cell type reached BH q < 0.05 in either diet (Results 3.3), and for identifying "
    "which cell types had the largest (even if non-significant) effect sizes as leads "
    "for a follow-up, adequately powered study."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_MKO_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["diet"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "Diet", "n (MKO vs WT)", "Mean MKO", "Mean WT", "Cohen's d",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_MKO_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")
doc.add_page_break()

# ================================================================ DATA S3 ==
data_heading(3, "Full lipogenic-gene correlation results — all 30 tests")
add_para(
    "Referenced in: Results 3.4, Figure 4C. Spearman correlations between "
    "Macrophage_Kupffer / S100A8hi_macrophage deconvolution scores and five lipogenic "
    "genes (Cd36, Fasn, Plin2, Pparg, Scd1), computed in three overlapping sample "
    "subsets (all 19 HFD samples, axis-1 HFD only, axis-2 HFD only). Generated by "
    "scripts/11_statistical_rigor_addendum.R. Useful for: seeing the BH correction "
    "applied across all 30 tests at once (the source of the q-values quoted in the "
    "main text), and for checking genes/subsets not singled out in Figure 4."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_lipid_correlation_BH.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["gene"], d["subset"], d["n"],
        fmt(d["r"], 2), fmt(d["p_value"], 3),
        fmt(d["p_BH_within_subset"], 3), fmt(d["p_BH_all30"], 3),
    ])
make_table(
    ["Cell type", "Gene", "Subset", "n", "Spearman r", "p-value",
     "BH-q (within subset)", "BH-q (all 30 tests)"],
    out_rows, font_size=8,
)
source_line("results/11_lipid_correlation_BH.csv", "scripts/11_statistical_rigor_addendum.R")
doc.add_page_break()

# ================================================================ DATA S4 ==
data_heading(4, "GSE156057: marker-gene expression by cluster — all 40 clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5A. Percent of cells expressing "
    "each of 17 lineage/identity marker genes, for every one of the 40 clusters "
    "identified in the reclustered GSE156057 (CD45+-sorted) dataset — not only the 6 "
    "clusters (3 candidate S100A8-hi, 1 neutrophil, 2 Kupffer) shown in Figure 5A. "
    "Generated by external_validation/scripts/03_gse156057_qc_cluster.R. Useful for: "
    "independently checking the S100A8-hi / neutrophil / Kupffer classification "
    "criteria (Methods 2.7) against every cluster, not just the ones we selected as "
    "examples."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=7)
source_line("external_validation/results/gse156057_pct_expr_by_cluster.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S5 ==
data_heading(5, "GSE156057: top 5 differential marker genes per cluster (all 40 clusters)")
add_para(
    "Referenced in: Results 3.5, Methods 2.7. The five most significantly "
    "up-regulated marker genes (Seurat FindAllMarkers, Wilcoxon rank-sum, "
    "avg_log2FC-ranked) for each of the 40 GSE156057 clusters, condensed from the "
    "complete differential-expression table. Generated by external_validation/"
    "scripts/03_gse156057_qc_cluster.R. Useful for: independently naming/annotating "
    "any cluster referenced by number in Data S4 or Figure 5, without needing to "
    "open the full marker table. The complete, unabbreviated result (24,030 gene x "
    "cluster comparisons, all with p-values) is provided separately as "
    "external_validation/results/gse156057_cluster_markers.csv in the code "
    "repository (too large to reproduce in full here)."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_cluster_top5.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cluster"].strip('"'), d["gene"].strip('"'),
        fmt(d["avg_log2FC"], 2), fmt(d["pct.1"], 2), fmt(d["pct.2"], 2),
        fmt(d["p_val"], 3), fmt(d["p_val_adj"], 3),
    ])
make_table(
    ["Cluster", "Gene", "avg log2FC", "% expr. (in cluster)", "% expr. (other clusters)",
     "p-value", "BH-adj p-value"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_cluster_top5.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S6 ==
data_heading(6, "GSE156057: S100A8-hi / Kupffer / Neutrophil proportions by diet and timepoint")
add_para(
    "Referenced in: Results 3.5, Figure 5B. Per-sample cell counts and proportions "
    "(of all CD45+ cells sequenced in that sample) for the combined S100A8-hi "
    "macrophage clusters, the Kupffer clusters, and the neutrophil cluster, across "
    "all 6 GSE156057 samples (standard diet [SD] / western diet [WD] x 12/24/36 "
    "weeks). \"Other\" comprises all remaining clusters (T/B/NK/DC/etc.). Generated "
    "by external_validation/scripts/04_gse156057_proportions.R. Useful for: the "
    "exact per-sample numbers behind the WD/SD ratios quoted in Results 3.5 (1.45 "
    "at 12 weeks, 1.21 at 24 weeks, 0.81 at 36 weeks) and behind Figure 5B."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_S100A8hi_proportions.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["sample"].strip('"'), d["diet"].strip('"'), d["timepoint"].strip('"'),
        d["cell_class"].strip('"'), d["n"], d["total"],
        f"{float(d['proportion'])*100:.2f}%",
    ])
make_table(
    ["Sample", "Diet", "Timepoint", "Cell class", "n cells", "Total CD45+ cells", "Proportion"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_S100A8hi_proportions.csv",
            "external_validation/scripts/04_gse156057_proportions.R")
doc.add_page_break()

# ================================================================ DATA S7 ==
data_heading(7, "GSE166504: marker-gene expression by cluster — all 18 myeloid clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5C. Percent of cells expressing "
    "12 lineage/identity marker genes for every one of the 18 clusters identified "
    "within the reclustered myeloid compartment of GSE166504 (whole-liver, true "
    "biological replicates). Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: the full data behind Figure 5C's "
    "claim that S100a8 positivity forms a gradient rather than isolating a discrete "
    "cluster among monocyte/macrophage-lineage populations."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=8)
source_line("external_validation/results/gse166504_pct_expr_by_cluster.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ================================================================ DATA S8 ==
data_heading(8, "GSE166504: cluster identity cross-tabulation vs author-provided cell-type labels")
add_para(
    "Referenced in: Methods 2.7, Results 3.5. Number of cells per re-clustering "
    "cluster (rows) assigned to each of the original authors' three coarse "
    "myeloid cell-type labels (columns: Kupffer cells, Monocyte/Monocyte-derived "
    "macrophage, Neutrophils), used to determine the \"dominant cell-type label\" "
    "coloring in Figure 5C. Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: checking cluster purity — e.g., "
    "whether a given cluster is a clean match to one author label or a mixture."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_cluster_vs_authorlabel.csv"))
out_rows = []
for row in rows:
    out_rows.append([row[0].strip('"')] + row[1:])
make_table(["Cluster"] + headers[1:], out_rows, font_size=9)
source_line("external_validation/results/gse166504_cluster_vs_authorlabel.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")

print("Document complete.")
doc.save(OUT_PATH)
print(f"Saved to {OUT_PATH}")
