#!/usr/bin/env python3
"""Builds supplemental_data.docx: full source-data tables (Data S1-S8) for the
project1 S100A8+ macrophage deconvolution manuscript, each with a description of
what it contains, how it was generated, and what it is useful for."""

import os
import csv
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

REPO = os.path.join(os.path.dirname(__file__), "..")
RESULTS = os.path.join(REPO, "results")
EXT_RESULTS = os.path.join(REPO, "external_validation", "results")
FIG = os.path.join(REPO, "figures")
EXT_FIG = os.path.join(REPO, "external_validation", "figures")
OUT_PATH = os.path.join(os.path.dirname(__file__), "supplemental_data.docx")

doc = Document()

# ---------------------------------------------------------------- styles ---
section = doc.sections[0]
section.orientation = WD_ORIENT.LANDSCAPE
section.page_width, section.page_height = Inches(11), Inches(8.5)
for m in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
    setattr(section, m, Inches(0.7))

normal = doc.styles["Normal"]
normal.font.name = "Times New Roman"
normal.font.size = Pt(11)
normal.paragraph_format.space_after = Pt(8)
normal.paragraph_format.line_spacing = 1.3
rpr = normal.element.get_or_add_rPr()
rFonts = rpr.find(qn("w:rFonts"))
if rFonts is None:
    rFonts = OxmlElement("w:rFonts")
    rpr.append(rFonts)
rFonts.set(qn("w:eastAsia"), "Times New Roman")

for lvl, size, bold in [(1, 15, True), (2, 13, True)]:
    style = doc.styles[f"Heading {lvl}"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(size)
    style.font.bold = bold
    style.font.color.rgb = RGBColor(0, 0, 0)
    style.paragraph_format.space_before = Pt(14)
    style.paragraph_format.space_after = Pt(6)


def add_para(text, size=11, bold=False, italic=False, space_after=8):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    r.font.size = Pt(size)
    p.paragraph_format.space_after = Pt(space_after)
    return p


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    return rows[0], rows[1:]


def fmt(val, decimals=None):
    if val is None or val == "":
        return ""
    try:
        f = float(val)
    except ValueError:
        return val.strip('"')
    if decimals is None:
        return str(val)
    if abs(f) < 0.001 and f != 0:
        return f"{f:.2e}"
    return f"{f:.{decimals}f}"


def make_table(headers, rows, font_size=8, col_widths=None):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = table.rows[0].cells
    for i, h in enumerate(headers):
        run = hdr[i].paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(font_size)
    for row in rows:
        cells = table.add_row().cells
        for i, val in enumerate(row):
            run = cells[i].paragraphs[0].add_run(str(val))
            run.font.size = Pt(font_size)
    if col_widths:
        for row in table.rows:
            for i, w in enumerate(col_widths):
                row.cells[i].width = Inches(w)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)
    return table


def data_heading(num, title):
    doc.add_heading(f"Data S{num}. {title}", level=2)


def source_line(path, script):
    p = doc.add_paragraph()
    r = p.add_run(f"Source file: {path}   |   Generated by: {script}")
    r.italic = True
    r.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(10)


def fig_heading(num, title):
    doc.add_heading(f"Figure S{num}. {title}", level=2)


def add_figure(fig_root, png_name, width_in, description, script):
    doc.add_picture(os.path.join(fig_root, png_name), width=Inches(width_in))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_para(description)
    p = doc.add_paragraph()
    r = p.add_run(f"Source file: {os.path.relpath(fig_root, REPO)}/{png_name}   |   Generated by: {script}")
    r.italic = True
    r.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(14)


# ============================================================ TITLE PAGE ===
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Supplemental Data")
r.bold = True
r.font.size = Pt(18)
title.paragraph_format.space_after = Pt(6)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = subtitle.add_run(
    "Cross-Validated Deconvolution Identifies General Hepatic Macrophage "
    "Burden, Not an S100A8-Hi Subset, as the Lipogenic-Gene Correlate in "
    "Mouse MASLD"
)
r.italic = True
r.font.size = Pt(13)
subtitle.paragraph_format.space_after = Pt(20)

intro = doc.add_paragraph()
intro.add_run(
    "This document provides full source-data tables (Data S1-S26) and figures "
    "(Figure S1-S30) supporting the statistical claims in the main manuscript, "
    "including its follow-up analysis (Section 3.6) of the origin, transcriptional "
    "trigger, and fate of the S100A8-hi macrophage population. Each entry states "
    "what it contains, how it was generated, and what question it lets the reader "
    "check independently. Full analysis code is at "
    "https://github.com/bioinform25/project1; the exact source CSV/PNG for each "
    "item is named below it. Numeric values are rounded for display; unrounded "
    "values are in the source CSVs."
)
doc.add_page_break()

# ================================================================ DATA S1 ==
data_heading(1, "Full axis-1 (WT vs Bcl2TG, HFD) deconvolution statistics — all 12 cell types")
add_para(
    "Referenced in: Results 3.2 (\"Four additional cell types reached BH q = 0.024...\"), "
    "Figure 2. Every cell type's Wilcoxon/Welch comparison, Cohen's d, 95% CI and "
    "BH-adjusted q-values for the axis-1 validation cohort (n = 5 WT vs n = 5 Bcl2TG, "
    "HFD) are reported here, not only the two highlighted in the main text (Macrophage_"
    "Kupffer, S100A8hi_macrophage). Generated by scripts/11_statistical_rigor_addendum.R. "
    "Useful for: checking whether a specific cell type not discussed in the main text "
    "reached significance, and for re-deriving Figure 2's underlying numbers."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_axis1_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        f"[{fmt(d['ci95_lo'], 2)}, {fmt(d['ci95_hi'], 2)}]",
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "n (WT vs TG)", "Mean WT", "Mean TG", "Cohen's d", "95% CI (mean diff)",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_axis1_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")

# ================================================================ DATA S2 ==
data_heading(2, "Full axis-2 (WT vs MKO) deconvolution statistics — all 12 cell types x 2 diets")
add_para(
    "Referenced in: Results 3.3, Figure 3. Every cell type's WT-vs-MKO comparison in "
    "both chow and HFD, including the two cell types with the largest nominal, "
    "BH-uncorrected effects (Neutrophil, Mast_cell) highlighted in the main text. "
    "Generated by scripts/11_statistical_rigor_addendum.R. Useful for: confirming that "
    "no cell type reached BH q < 0.05 in either diet (Results 3.3), and for identifying "
    "which cell types had the largest (even if non-significant) effect sizes as leads "
    "for a follow-up, adequately powered study."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_MKO_stats_full.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["diet"],
        f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_x"], 2), fmt(d["mean_y"], 2),
        fmt(d["cohens_d"], 2),
        fmt(d["welch_t_p"], 3), fmt(d["wilcoxon_p"], 3),
        fmt(d["welch_p_BH"], 3), fmt(d["wilcoxon_p_BH"], 3),
    ])
make_table(
    ["Cell type", "Diet", "n (MKO vs WT)", "Mean MKO", "Mean WT", "Cohen's d",
     "Welch p", "Wilcoxon p", "Welch BH-q", "Wilcoxon BH-q"],
    out_rows, font_size=8,
)
source_line("results/11_MKO_stats_full.csv", "scripts/11_statistical_rigor_addendum.R")
add_para(
    "This table supersedes the earlier, pre-rigor-audit results/08_MKO_stats.csv "
    "(Welch t-test only, no Cohen's d/CI, no Wilcoxon) with the same underlying "
    "comparisons; the original file is retained in the repository for provenance but "
    "its content is fully contained in the table above.",
    size=9,
)
doc.add_page_break()

# ================================================================ DATA S3 ==
data_heading(3, "Full lipogenic-gene correlation results — all 30 tests")
add_para(
    "Referenced in: Results 3.4, Figure 4C. Spearman correlations between "
    "Macrophage_Kupffer / S100A8hi_macrophage deconvolution scores and five lipogenic "
    "genes (Cd36, Fasn, Plin2, Pparg, Scd1), computed in three overlapping sample "
    "subsets (all 19 HFD samples, axis-1 HFD only, axis-2 HFD only). Generated by "
    "scripts/11_statistical_rigor_addendum.R. Useful for: seeing the BH correction "
    "applied across all 30 tests at once (the source of the q-values quoted in the "
    "main text), and for checking genes/subsets not singled out in Figure 4."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_lipid_correlation_BH.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cell_type"], d["gene"], d["subset"], d["n"],
        fmt(d["r"], 2), fmt(d["p_value"], 3),
        fmt(d["p_BH_within_subset"], 3), fmt(d["p_BH_all30"], 3),
    ])
make_table(
    ["Cell type", "Gene", "Subset", "n", "Spearman r", "p-value",
     "BH-q (within subset)", "BH-q (all 30 tests)"],
    out_rows, font_size=8,
)
source_line("results/11_lipid_correlation_BH.csv", "scripts/11_statistical_rigor_addendum.R")
add_para(
    "This table supersedes the earlier, pre-rigor-audit results/09_lipid_gene_"
    "correlation.csv (same 30 correlations, no BH-FDR correction applied); the "
    "original file is retained in the repository for provenance but its content is "
    "fully contained in the table above.",
    size=9,
)
doc.add_page_break()

# ================================================================ DATA S4 ==
data_heading(4, "GSE156057: marker-gene expression by cluster — all 40 clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5A. Percent of cells expressing "
    "each of 17 lineage/identity marker genes, for every one of the 40 clusters "
    "identified in the reclustered GSE156057 (CD45+-sorted) dataset — not only the 6 "
    "clusters (3 candidate S100A8-hi, 1 neutrophil, 2 Kupffer) shown in Figure 5A. "
    "Generated by external_validation/scripts/03_gse156057_qc_cluster.R. Useful for: "
    "independently checking the S100A8-hi / neutrophil / Kupffer classification "
    "criteria (Methods 2.7) against every cluster, not just the ones we selected as "
    "examples."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=7)
source_line("external_validation/results/gse156057_pct_expr_by_cluster.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S5 ==
data_heading(5, "GSE156057: top 5 differential marker genes per cluster (all 40 clusters)")
add_para(
    "Referenced in: Results 3.5, Methods 2.7. The five most significantly "
    "up-regulated marker genes (Seurat FindAllMarkers, Wilcoxon rank-sum, "
    "avg_log2FC-ranked) for each of the 40 GSE156057 clusters, condensed from the "
    "complete differential-expression table. Generated by external_validation/"
    "scripts/03_gse156057_qc_cluster.R. Useful for: independently naming/annotating "
    "any cluster referenced by number in Data S4 or Figure 5, without needing to "
    "open the full marker table. The complete, unabbreviated result (24,030 gene x "
    "cluster comparisons, all with p-values) is provided separately as "
    "external_validation/results/gse156057_cluster_markers.csv in the code "
    "repository (too large to reproduce in full here)."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_cluster_top5.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["cluster"].strip('"'), d["gene"].strip('"'),
        fmt(d["avg_log2FC"], 2), fmt(d["pct.1"], 2), fmt(d["pct.2"], 2),
        fmt(d["p_val"], 3), fmt(d["p_val_adj"], 3),
    ])
make_table(
    ["Cluster", "Gene", "avg log2FC", "% expr. (in cluster)", "% expr. (other clusters)",
     "p-value", "BH-adj p-value"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_cluster_top5.csv",
            "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

# ================================================================ DATA S6 ==
data_heading(6, "GSE156057: S100A8-hi / Kupffer / Neutrophil proportions by diet and timepoint")
add_para(
    "Referenced in: Results 3.5, Figure 5B. Per-sample cell counts and proportions "
    "(of all CD45+ cells sequenced in that sample) for the combined S100A8-hi "
    "macrophage clusters, the Kupffer clusters, and the neutrophil cluster, across "
    "all 6 GSE156057 samples (standard diet [SD] / western diet [WD] x 12/24/36 "
    "weeks). \"Other\" comprises all remaining clusters (T/B/NK/DC/etc.). Generated "
    "by external_validation/scripts/04_gse156057_proportions.R. Useful for: the "
    "exact per-sample numbers behind the WD/SD ratios quoted in Results 3.5 (1.45 "
    "at 12 weeks, 1.21 at 24 weeks, 0.81 at 36 weeks) and behind Figure 5B."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse156057_S100A8hi_proportions.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["sample"].strip('"'), d["diet"].strip('"'), d["timepoint"].strip('"'),
        d["cell_class"].strip('"'), d["n"], d["total"],
        f"{float(d['proportion'])*100:.2f}%",
    ])
make_table(
    ["Sample", "Diet", "Timepoint", "Cell class", "n cells", "Total CD45+ cells", "Proportion"],
    out_rows, font_size=8,
)
source_line("external_validation/results/gse156057_S100A8hi_proportions.csv",
            "external_validation/scripts/04_gse156057_proportions.R")
doc.add_page_break()

# ================================================================ DATA S7 ==
data_heading(7, "GSE166504: marker-gene expression by cluster — all 18 myeloid clusters")
add_para(
    "Referenced in: Results 3.5, Methods 2.7, Figure 5C. Percent of cells expressing "
    "12 lineage/identity marker genes for every one of the 18 clusters identified "
    "within the reclustered myeloid compartment of GSE166504 (whole-liver, true "
    "biological replicates). Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: the full data behind Figure 5C's "
    "claim that S100a8 positivity forms a gradient rather than isolating a discrete "
    "cluster among monocyte/macrophage-lineage populations."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_pct_expr_by_cluster.csv"))
gene_cols = headers[1:]
out_rows = []
for row in rows:
    cluster = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([cluster] + vals)
make_table(["Cluster"] + gene_cols, out_rows, font_size=8)
source_line("external_validation/results/gse166504_pct_expr_by_cluster.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ================================================================ DATA S8 ==
data_heading(8, "GSE166504: cluster identity cross-tabulation vs author-provided cell-type labels")
add_para(
    "Referenced in: Methods 2.7, Results 3.5. Number of cells per re-clustering "
    "cluster (rows) assigned to each of the original authors' three coarse "
    "myeloid cell-type labels (columns: Kupffer cells, Monocyte/Monocyte-derived "
    "macrophage, Neutrophils), used to determine the \"dominant cell-type label\" "
    "coloring in Figure 5C. Generated by external_validation/scripts/"
    "02_gse166504_cluster_annotate.R. Useful for: checking cluster purity — e.g., "
    "whether a given cluster is a clean match to one author label or a mixture."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_cluster_vs_authorlabel.csv"))
out_rows = []
for row in rows:
    out_rows.append([row[0].strip('"')] + row[1:])
make_table(["Cluster"] + headers[1:], out_rows, font_size=9)
source_line("external_validation/results/gse166504_cluster_vs_authorlabel.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ================================================================ DATA S9 ==
data_heading(9, "Monocyte-recruitment vs. resident-Kupffer marker panel, by refined origin group")
add_para(
    "Referenced in: Methods 2.2, Results 3.1, Section 4 (Discussion). Percent of "
    "cells expressing each of 12 literature-established monocyte-recruitment "
    "(Ly6c2, Ccr2, Sell, Plac8, Chil3), resident-Kupffer (Clec4f, Timd4, Vsig4, "
    "Cd5l, Marco) and lipid-associated-macrophage (Trem2, Gpnmb) marker genes, "
    "for S100A8hi_macrophage, Neutrophil, and the Macrophage_Kupffer compartment "
    "split into its two transcriptionally distinct constituent subsets: "
    "Kupffer_resident (original clusters 18+10, Clec4f/Vsig4/Cd5l-high) and "
    "Macrophage_MoMF_LAM (original clusters 5+11, Ccr2/Plac8-high, partially "
    "Trem2/Gpnmb-high). This split was motivated by an initial sanity check "
    "(during follow-up analysis) showing that a single merged Macrophage_Kupffer "
    "group scored unexpectedly high on monocyte-recruitment markers -- "
    "investigating why revealed that two of its four constituent subclusters "
    "(67% of its cells) carry a Ccr2-high monocyte-derived signature rather than "
    "a resident-Kupffer one. Generated by scripts/13_origin_signature_scoring.R. "
    "Useful for: verifying the Section 3.1/Section 4 claim that S100A8hi_"
    "macrophage lacks the classical Ccr2-dependent monocyte-recruitment "
    "signature (unlike the Ccr2-high subset of Macrophage_Kupffer), and for "
    "seeing the full 12-gene panel behind that conclusion rather than the two "
    "or three genes highlighted in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "13_origin_marker_panel_percluster.csv"))
pct_genes = ["Ly6c2", "Ccr2", "Sell", "Plac8", "Chil3", "Clec4f", "Timd4", "Vsig4", "Cd5l", "Marco", "Trem2", "Gpnmb"]
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d[gene + '_pct']) * 100:.1f}%" for gene in pct_genes])
make_table(["Origin group"] + [f"{g} (% pos.)" for g in pct_genes], out_rows, font_size=8)
source_line("results/13_origin_marker_panel_percluster.csv", "scripts/13_origin_signature_scoring.R")
add_para(
    "The per-cell values these per-cluster summaries are computed from (one row per "
    "cell, all four origin groups, MonocyteScore/ResidentScore) are available as "
    "results/13_origin_scores_primary_percell.csv in the code repository -- not "
    "reproduced here as a table (thousands of rows).",
    size=9,
)
doc.add_page_break()

# =============================================================== DATA S10 ==
data_heading(10, "Origin composite-score statistics, primary reference (secondary evidence to Data S9)")
add_para(
    "Referenced in: Section 4 (Discussion). Seurat AddModuleScore composite statistics "
    "(Wilcoxon/Welch, Cohen's d, BH-corrected within this 8-test family) for the "
    "monocyte-recruitment and resident-Kupffer composite scores across all pairwise "
    "comparisons of the four refined origin groups. Reported as secondary evidence "
    "alongside Data S9's per-gene panel because composite module scores can be skewed "
    "by individual non-specific genes within a signature (observed during this analysis: "
    "Ly6c2/Sell/Chil3 are not monocyte-lineage-specific in this dataset, being highly "
    "expressed in Neutrophil too -- see Data S9). Generated by "
    "scripts/13_origin_signature_scoring.R. Useful for: the full statistical backing "
    "for every pairwise composite-score comparison mentioned in the text."
)
headers, rows = read_csv(os.path.join(RESULTS, "13_origin_scores_primary_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("results/13_origin_scores_primary_stats.csv", "scripts/13_origin_signature_scoring.R")

# =============================================================== DATA S11 ==
data_heading(11, "Origin-signature score comparisons, GSE156057 (cross-dataset replication attempt)")
add_para(
    "Referenced in: Section 4 (Discussion). Same composite-score comparison as Data S10 "
    "(S100A8hi_macrophage vs. Kupffer vs. Neutrophil), repeated in the independent "
    "GSE156057 dataset. Unlike the primary reference, S100A8hi_macrophage here scores "
    "higher, not lower, on the monocyte-recruitment composite than the (single, "
    "unsplit) Kupffer cluster group -- per-gene inspection (Data S4) showed this "
    "reflects heterogeneity within GSE156057's own 3-cluster S100A8hi candidate set "
    "(Ccr2 ranges 2.6%-74.7% across the three clusters), mirroring the same "
    "within-group heterogeneity phenomenon documented in Data S9 for the primary "
    "reference's Macrophage_Kupffer label, rather than a clean replication or "
    "contradiction. Generated by "
    "external_validation/scripts/06_origin_signature_scoring.R. Useful for: seeing "
    "why composite scores should not be over-interpreted at this cluster resolution "
    "without the underlying per-gene breakdown."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse156057_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("external_validation/results/06_origin_scores_gse156057_stats.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")
doc.add_page_break()

# =============================================================== DATA S12 ==
data_heading(12, "Origin-signature score vs. S100a8 expression, GSE166504 (cluster-level correlation)")
add_para(
    "Referenced in: Section 4 (Discussion). GSE166504 has no discrete S100A8hi cluster "
    "(only a continuous gradient, Results 3.5), so origin scores are tested here as a "
    "cluster-level correlation instead of a group comparison: across the 18 myeloid "
    "clusters, does average S100a8 expression track more closely with the "
    "monocyte-recruitment score or the resident-Kupffer score? Resident score showed a "
    "borderline negative correlation (Spearman rho = -0.47, p = 0.05, i.e. higher S100a8 "
    "weakly tracks away from resident identity); monocyte-recruitment score did not "
    "(rho = 0.21, p = 0.41). Generated by "
    "external_validation/scripts/06_origin_signature_scoring.R. Useful for: the full "
    "per-cluster values behind this correlation, and the correlation statistics table."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse166504_correlation.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["score"].strip('"'), d["n_clusters"], fmt(d["spearman_rho"], 3), fmt(d["p_value"], 3)])
make_table(["Score", "n clusters", "Spearman rho", "p-value"], out_rows, font_size=9)
source_line("external_validation/results/06_origin_scores_gse166504_correlation.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")

headers2, rows2 = read_csv(os.path.join(EXT_RESULTS, "06_origin_scores_gse166504_cluster_avg.csv"))
out_rows2 = []
for row in rows2:
    d = dict(zip(headers2, row))
    out_rows2.append([d["seurat_clusters"].strip('"'), fmt(d["S100a8_expr"], 3),
                       fmt(d["MonocyteScore"], 3), fmt(d["ResidentScore"], 3), d["n_cells"]])
make_table(["Cluster", "S100a8 avg. expr.", "Monocyte score (avg.)", "Resident score (avg.)", "n cells"],
           out_rows2, font_size=9)
source_line("external_validation/results/06_origin_scores_gse166504_cluster_avg.csv",
            "external_validation/scripts/06_origin_signature_scoring.R")
doc.add_page_break()

# =============================================================== DATA S13 ==
data_heading(13, "TF mRNA vs. S100a9 expression / S100A8hi_macrophage score, bulk RNA-seq (all 34 samples)")
add_para(
    "Referenced in: Results 3.6, Methods 2.2/2.3. The original paper proposed, but did "
    "not test, that C/EBP or AP-1 family transcription factors regulate S100A8 "
    "induction. Formal TF activity inference (decoupleR + CollecTRI/DoRothEA) was "
    "attempted but failed in this environment due to a currently open upstream bug in "
    "OmnipathR's organism database (GitHub saezlab/OmnipathR issues #128, #121 -- "
    "reproduced even after updating to the latest GitHub development version, and "
    "affecting other users independently of this machine). As a transparent fallback, "
    "TF mRNA expression itself was used as a proxy (AP-1 genes are classic "
    "immediate-early genes whose own expression is a standard activation readout). "
    "Spearman correlation of each TF gene's bulk expression against S100a9 expression "
    "and against the deconvolved S100A8hi_macrophage score, in all 34 samples and in "
    "the 19-sample HFD-only subset, BH-corrected within each subset x target family "
    "(9 tests). No TF reached BH q < 0.05 against either target in either subset. "
    "Generated by scripts/14_tf_activity_inference.R. Useful for: the full correlation "
    "table behind the Results 3.6 null finding, including genes/subsets not singled "
    "out in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_bulk_correlation.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["tf_family"].strip('"'), d["tf_gene"].strip('"'), d["target"].strip('"'), d["subset"].strip('"'),
        fmt(d["r"], 3), fmt(d["p_value"], 3), d["n"], fmt(d["p_BH"], 3),
    ])
make_table(["TF family", "TF gene", "Target", "Subset", "Spearman r", "p-value", "n", "BH-q"],
           out_rows, font_size=8)
source_line("results/14_tf_bulk_correlation.csv", "scripts/14_tf_activity_inference.R")
doc.add_page_break()

# =============================================================== DATA S14 ==
data_heading(14, "C/EBP and AP-1 family TF mRNA panel by refined origin group, primary scRNA reference")
add_para(
    "Referenced in: Results 3.6. Percent of cells expressing (and average expression "
    "of) each of 9 C/EBP-family (Cebpa, Cebpb, Cebpd) and AP-1-family (Fos, Fosb, Jun, "
    "Junb, Jund, Atf3) transcription factor genes, across the same four refined origin "
    "groups used in Data S9. Notably, Cebpa -- the C/EBP paralog most implicated in "
    "myeloid inflammatory gene induction in the literature -- is lowest in "
    "S100A8hi_macrophage (4.4%) and highest in Macrophage_MoMF_LAM (51.1%), the "
    "opposite of what a simple 'C/EBP drives S100A8hi identity' model would predict. "
    "Generated by scripts/14_tf_activity_inference.R. Useful for: checking any "
    "individual TF gene's expression pattern beyond the two (Cebpa, Ap1Score) "
    "highlighted in the main text."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_scrna_percluster.csv"))
tf_genes = ["Cebpa", "Cebpb", "Cebpd", "Fos", "Fosb", "Jun", "Junb", "Jund", "Atf3"]
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d[gene + '_pct']) * 100:.1f}%" for gene in tf_genes])
make_table(["Origin group"] + [f"{g} (% pos.)" for g in tf_genes], out_rows, font_size=8)
source_line("results/14_tf_scrna_percluster.csv", "scripts/14_tf_activity_inference.R")

# =============================================================== DATA S15 ==
data_heading(15, "C/EBP-score and AP1-score composite comparisons, primary scRNA reference")
add_para(
    "Referenced in: Results 3.6. Composite AddModuleScore statistics (same design as "
    "Data S10) for the C/EBP-family and AP-1-family gene sets, across pairwise "
    "comparisons of S100A8hi_macrophage against the other three refined origin groups. "
    "S100A8hi_macrophage's Ap1Score does not differ from Macrophage_MoMF_LAM's "
    "(Cohen's d = 0.02, Wilcoxon p = 0.74), despite differing significantly from both "
    "Kupffer_resident and Neutrophil -- i.e. AP-1 activity alone does not distinguish "
    "S100A8hi_macrophage from the Ccr2-high MoMF/LAM population the way Ccr2 itself "
    "does (Data S9). Generated by scripts/14_tf_activity_inference.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "14_tf_scrna_stats.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([
        d["comparison"].strip('"'), d["score"].strip('"'), f"{d['n_x']} vs {d['n_y']}",
        fmt(d["mean_diff"], 2), fmt(d["cohens_d"], 2), fmt(d["wilcoxon_p"], 4), fmt(d["wilcoxon_p_BH"], 4),
    ])
make_table(["Comparison", "Score", "n (x vs y)", "Mean diff", "Cohen's d", "Wilcoxon p", "Wilcoxon BH-q"],
           out_rows, font_size=8)
source_line("results/14_tf_scrna_stats.csv", "scripts/14_tf_activity_inference.R")
doc.add_page_break()

# =============================================================== DATA S16 ==
data_heading(16, "S100A8hi_macrophage vs. Kupffer proportion trend over time, GSE156057")
add_para(
    "Referenced in: Results 3.6. Linear regression slope of cell-class proportion "
    "against timepoint (12/24/36 weeks), fit separately for S100A8hi_macrophage and "
    "Kupffer, within each diet arm (SD, WD; n = 3 timepoints per diet, one sample "
    "each -- severely underpowered, direction only, not a statistical claim). Under "
    "WD, S100A8hi_macrophage's slope is negative (-0.0010/week) while Kupffer's is "
    "positive (+0.0003/week) -- directionally consistent with a maturation model "
    "(S100A8hi declining as a Kupffer-like population accumulates) but neither slope "
    "is statistically distinguishable from zero at this sample size (p = 0.17, "
    "p = 0.60). Generated by scripts/15_fate_trajectory.R. Useful for: the exact "
    "slope/p-value numbers behind the Results 3.6 statement that this trend is "
    "directionally suggestive but not statistically resolvable."
)
headers, rows = read_csv(os.path.join(RESULTS, "15_fate_compositional_trend.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["cell_class"].strip('"'), d["diet"].strip('"'), d["n"], fmt(d["slope"], 5), fmt(d["p_value"], 3)])
make_table(["Cell class", "Diet", "n timepoints", "Slope (proportion/week)", "p-value"], out_rows, font_size=9)
source_line("results/15_fate_compositional_trend.csv", "scripts/15_fate_trajectory.R")

# =============================================================== DATA S17 ==
data_heading(17, "PCA-space nearest-neighbor composition by refined origin group (transcriptional continuity)")
add_para(
    "Referenced in: Results 3.6, Section 4 (Discussion). For each cell in the four "
    "refined origin groups, the origin-group identity of its k = 30 nearest neighbors "
    "in a PCA space computed from just these four groups (to avoid dilution by "
    "unrelated cell types), averaged per group. High on-diagonal values indicate "
    "discrete, well-separated states; off-diagonal 'leakage' indicates a transcriptional "
    "continuum. S100A8hi_macrophage is 96.2% self-neighboring (1.6% leakage into "
    "Macrophage_MoMF_LAM, 2.0% into Kupffer_resident), while Kupffer_resident and "
    "Macrophage_MoMF_LAM leak into each other at 7.3%/2.6% -- consistent with the "
    "established monocyte-to-Kupffer differentiation continuum (Guilliams et al. 2022; "
    "Scott et al. 2016; Bonnardel et al. 2019 -- see main-text references 11-13) and "
    "arguing against S100A8hi_macrophage being an early point on that same trajectory. "
    "Generated by scripts/15_fate_trajectory.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "15_fate_neighbor_purity.csv"))
group_order = ["S100A8hi_macrophage", "Kupffer_resident", "Macrophage_MoMF_LAM", "Neutrophil"]
rows_by_group = {row[0].strip('"'): dict(zip(headers, row)) for row in rows}
out_rows = []
for g in group_order:
    d = rows_by_group[g]
    out_rows.append([g] + [f"{float(d['pct_neighbors_' + g2]) * 100:.1f}%" for g2 in group_order] + [d["n_cells"]])
make_table(["Own group"] + [f"% neighbors: {g}" for g in group_order] + ["n cells"], out_rows, font_size=8)
source_line("results/15_fate_neighbor_purity.csv", "scripts/15_fate_trajectory.R")
doc.add_page_break()

# =============================================================== DATA S18 ==
data_heading(18, "scRNA-seq QC summary: cells before/after filtering")
add_para(
    "Referenced in: Methods 2.2. Per-sample (WT, TG) cell counts before and after the "
    "QC filter (200 < nFeature_RNA < 6,000, nCount_RNA < 30,000, percent.mt < 25%) "
    "applied to the raw GSE285615 h5 matrices. Generated by scripts/01_scRNA_qc.R. "
    "Useful for: confirming the exact cell-loss numbers quoted in Methods 2.2 "
    "(320/11,579 WT cells and 277/8,158 TG cells removed)."
)
headers, rows = read_csv(os.path.join(RESULTS, "01_qc_summary.csv"))
out_rows = [[dict(zip(headers, row))[h].strip('"') if h == "sample" else dict(zip(headers, row))[h]
             for h in headers] for row in rows]
make_table(["Sample", "n cells (pre-filter)", "n cells (post-filter)"], out_rows, font_size=10)
source_line("results/01_qc_summary.csv", "scripts/01_scRNA_qc.R")

# =============================================================== DATA S19 ==
data_heading(19, "Full-resolution (28-cluster) marker genes and cluster sizes, primary scRNA reference")
add_para(
    "Referenced in: Methods 2.2. Before collapsing to 12 final cell types (Section 2.2), "
    "the primary scRNA reference was clustered at resolution 0.8 into 28 clusters. This "
    "table gives the top-5 differential marker gene per cluster (Wilcoxon, "
    "avg_log2FC-ranked) and each cluster's cell count by genotype -- the direct evidence "
    "underlying the cluster-to-cell-type mapping described in Methods 2.2. The complete, "
    "unabbreviated marker table (all significant genes x all 28 clusters) is available "
    "separately as results/02_cluster_markers.csv in the code repository (too large to "
    "reproduce here). Generated by scripts/02_scRNA_cluster_annotate.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "02_cluster_top5_markers.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["cluster"].strip('"'), d["gene"].strip('"'), fmt(d["avg_log2FC"], 2),
                      fmt(d["pct.1"], 2), fmt(d["pct.2"], 2), fmt(d["p_val_adj"], 3)])
make_table(["Cluster", "Gene", "avg log2FC", "% expr. (in cluster)", "% expr. (other)", "BH-adj p"],
           out_rows, font_size=7)
source_line("results/02_cluster_top5_markers.csv (full table: results/02_cluster_markers.csv)",
            "scripts/02_scRNA_cluster_annotate.R")
doc.add_page_break()

headers2, rows2 = read_csv(os.path.join(RESULTS, "02_cluster_sizes_by_genotype.csv"))
out_rows2 = [[row[0].strip('"'), row[1], row[2]] for row in rows2]
make_table(["Cluster", "TG", "WT"], out_rows2, font_size=8)
source_line("results/02_cluster_sizes_by_genotype.csv", "scripts/02_scRNA_cluster_annotate.R")

# =============================================================== DATA S20 ==
data_heading(20, "Cell-type counts by genotype, 12-type resolution")
add_para(
    "Referenced in: Results 3.1. Number of cells per final annotated cell type (Methods "
    "2.2), split by genotype (WT, TG). This is the raw count table underlying Figure 1A "
    "and the proportions computed in Data S21. Generated by "
    "scripts/03_scRNA_annotate_finalize.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "03_celltype_counts_by_genotype.csv"))
out_rows = [[row[0].strip('"'), row[1], row[2]] for row in rows]
make_table(["Cell type", "TG", "WT"], out_rows, font_size=9)
source_line("results/03_celltype_counts_by_genotype.csv", "scripts/03_scRNA_annotate_finalize.R")

# =============================================================== DATA S21 ==
data_heading(21, "scRNA-observed cell-type proportions (ground truth) and TG/WT ratio")
add_para(
    "Referenced in: Results 3.1/3.2, Section 4 (Discussion). Cell-type proportions "
    "observed directly in the n=1-per-genotype scRNA reference, and the TG/WT ratio for "
    "each cell type -- used in Results 3.2 as a (low-confidence, n=1) reference point "
    "before the axis-1 bulk deconvolution validation, and discussed as a methodological "
    "cautionary example (Section 4: a single-mouse-pair ground truth gave the wrong "
    "direction for S100A8hi_macrophage, later corrected against the fully replicated "
    "bulk DESeq2 result). Generated by scripts/04_scRNA_ground_truth_props.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "04_ground_truth_TGvsWT_ratio.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["cell_type"].strip('"'), fmt(d["WT"], 4), fmt(d["TG"], 4), fmt(d["TG_over_WT"], 2)])
make_table(["Cell type", "Proportion, WT", "Proportion, TG", "TG / WT ratio"], out_rows, font_size=9)
source_line("results/04_ground_truth_TGvsWT_ratio.csv (per-cell counts: results/04_ground_truth_proportions.csv)",
            "scripts/04_scRNA_ground_truth_props.R")

# =============================================================== DATA S22 ==
data_heading(22, "Bulk RNA-seq sample metadata, all 34 samples")
add_para(
    "Referenced in: Methods 2.3. Sample-level metadata (axis, genotype, diet, group "
    "label) for all 34 GSE285614 bulk RNA-seq samples after parsing and merging the two "
    "source xlsx files (Methods 2.3). Generated by scripts/05_bulk_load_merge.R. Useful "
    "for: seeing exactly which samples belong to which axis/genotype/diet combination "
    "underlying every bulk analysis in this manuscript."
)
headers, rows = read_csv(os.path.join(RESULTS, "05_bulk_sample_metadata.csv"))
out_rows = [[c.strip('"') for c in row] for row in rows]
make_table(["Sample", "Axis", "Genotype", "Diet", "Group"], out_rows, font_size=7)
source_line("results/05_bulk_sample_metadata.csv", "scripts/05_bulk_load_merge.R")
doc.add_page_break()

# =============================================================== DATA S23 ==
data_heading(23, "Full deconvolution scores, all 34 bulk samples x 12 cell types")
add_para(
    "Referenced in: Methods 2.4, Results 3.2-3.4. The complete BisqueRNA "
    "MarkerBasedDecomposition output -- relative abundance (PC1) score for every one of "
    "the 12 annotated cell types, in all 34 bulk samples -- underlying every downstream "
    "comparison and correlation in Results 3.2-3.4 (not only the two cell types "
    "highlighted in the main text). The marker gene set used per cell type is available "
    "separately as results/06_celltype_markers.csv (too large to reproduce in full "
    "here; panel sizes are already summarized in Table S1 / Data S1's context). "
    "Generated by scripts/06_deconvolution.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "06_deconvolution_props.csv"))
cell_types = [h for h in headers if h not in ("sample", "axis", "genotype", "diet", "group")]
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["sample"].strip('"'), d["axis"].strip('"'), d["genotype"].strip('"'), d["diet"].strip('"')]
                     + [fmt(d[ct], 2) for ct in cell_types])
make_table(["Sample", "Axis", "Genotype", "Diet"] + cell_types, out_rows, font_size=6)
source_line("results/06_deconvolution_props.csv (marker genes used: results/06_celltype_markers.csv)",
            "scripts/06_deconvolution.R")
doc.add_page_break()

# =============================================================== DATA S24 ==
data_heading(24, "Axis-1 validation: original-paper marker-gene direction cross-check")
add_para(
    "Referenced in: Results 3.2. Two tables supporting the axis-1 validation logic "
    "(Methods 2.5, Results 3.2): (1) the original authors' own axis-1 DESeq2 "
    "log2FoldChange, p-value and direction for each canonical marker gene "
    "(S100a8/S100a9/Adgre1/Csf1r/Clec4f/Cd68/Cd3e/Ptprc), used as the high-confidence "
    "(n=5 vs n=5) reference direction; (2) the full per-cell-type comparison of "
    "deconvolution direction against both this high-confidence marker-gene direction and "
    "the low-confidence (n=1) scRNA ground-truth direction from Data S21. Generated by "
    "scripts/07_validate_axis1.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "07_marker_gene_direction_check.csv"))
out_rows = []
for row in rows:
    d = dict(zip(headers, row))
    out_rows.append([d["cell_type"].strip('"'), d["gene"].strip('"'), fmt(d["log2FoldChange"], 2),
                      fmt(d["pvalue"], 3), d["deseq_direction"].strip('"')])
make_table(["Cell type", "Gene", "log2FC (TG vs WT)", "p-value", "DESeq2 direction"], out_rows, font_size=9)
source_line("results/07_marker_gene_direction_check.csv", "scripts/07_validate_axis1.R")
doc.add_page_break()

headers2, rows2 = read_csv(os.path.join(RESULTS, "07_validation_stats.csv"))
out_rows2 = []
for row in rows2:
    d = dict(zip(headers2, row))
    out_rows2.append([
        d["cell_type"].strip('"'), fmt(d["diff_TG_minus_WT"], 2), fmt(d["p_value"], 3),
        d["decon_direction"].strip('"'), d["deseq_direction_majority"].strip('"'),
        d["primary_validation_match"].strip('"'), d["scrna_direction_match"].strip('"'),
    ])
make_table(["Cell type", "Diff (TG-WT)", "p", "Decon. direction", "DESeq2 direction",
            "Matches DESeq2?", "Matches n=1 scRNA?"], out_rows2, font_size=7)
source_line("results/07_validation_stats.csv", "scripts/07_validate_axis1.R")

# =============================================================== DATA S25 ==
data_heading(25, "Post-hoc statistical power / minimum detectable effect size (MDE)")
add_para(
    "Referenced in: Results 3.3, Section 4 (Discussion), Limitations. Minimum Cohen's d "
    "detectable at 80% power (alpha = 0.05, two-sample t-test) for the axis-2 (MKO) "
    "group sizes used in this study (n = 4 and n = 5 per group). This is the source of "
    "the \"Cohen's d >~ 2.0-2.4\" figure quoted wherever the MKO null result is "
    "discussed. Generated by scripts/11_statistical_rigor_addendum.R."
)
headers, rows = read_csv(os.path.join(RESULTS, "11_power_MDE.csv"))
out_rows = [[row[0], row[1]] for row in rows]
make_table(["n per group", "Min. detectable Cohen's d (80% power)"], out_rows, font_size=11)
source_line("results/11_power_MDE.csv", "scripts/11_statistical_rigor_addendum.R")

# =============================================================== DATA S26 ==
data_heading(26, "GSE166504: average expression by cluster (companion to Data S7)")
add_para(
    "Referenced in: Methods 2.7, Results 3.5. Average (not just percent-positive) "
    "expression of the same 12-gene marker panel as Data S7, for all 18 GSE166504 "
    "myeloid subclusters -- provided alongside the percent-expressing table since "
    "average expression can reveal graded differences that a percent-positive cutoff "
    "can mask, relevant to Results 3.5's \"gradient, not cluster\" finding. Generated by "
    "external_validation/scripts/02_gse166504_cluster_annotate.R."
)
headers, rows = read_csv(os.path.join(EXT_RESULTS, "gse166504_avg_expr_by_cluster.csv"))
gene_col = headers[0]
cluster_cols = headers[1:]
out_rows = []
for row in rows:
    gene = row[0].strip('"')
    vals = [fmt(v, 2) for v in row[1:]]
    out_rows.append([gene] + vals)
make_table(["Gene"] + cluster_cols, out_rows, font_size=7)
source_line("external_validation/results/gse166504_avg_expr_by_cluster.csv",
            "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

# ======================================================= SUPPLEMENTAL FIGURES ==
title2 = doc.add_paragraph()
title2.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title2.add_run("Supplemental Figures")
r.bold = True
r.font.size = Pt(16)
title2.paragraph_format.space_after = Pt(18)

fig_heading(1, "Origin/identity marker dot plot, primary scRNA reference")
add_figure(FIG, "13_origin_marker_dotplot.png", 7.5,
           "Dot plot of the 12-gene origin/identity marker panel (Data S9) across the four "
           "refined origin groups (S100A8hi_macrophage, Kupffer_resident, Macrophage_MoMF_LAM, "
           "Neutrophil), primary scRNA reference. Referenced in Results 3.1, Section 4.",
           "scripts/13_origin_signature_scoring.R")

fig_heading(2, "Monocyte-recruitment and resident-Kupffer composite scores by origin group, primary reference")
add_figure(FIG, "13_origin_scores_primary.png", 9.5,
           "Violin/boxplots of the two composite module scores (Data S10) across the four "
           "refined origin groups. Referenced in Section 4.",
           "scripts/13_origin_signature_scoring.R")

fig_heading(3, "Origin-signature composite scores by cell class, GSE156057")
add_figure(EXT_FIG, "06_origin_scores_gse156057.png", 9.5,
           "Same composite scores as Fig S2, computed in the independent GSE156057 dataset "
           "(Data S11). Referenced in Section 4.",
           "external_validation/scripts/06_origin_signature_scoring.R")

fig_heading(4, "Cluster-average S100a8 expression vs. origin scores, GSE166504")
add_figure(EXT_FIG, "06_origin_scores_gse166504.png", 9.5,
           "Cluster-level scatter of average S100a8 expression against the monocyte-recruitment "
           "and resident-Kupffer composite scores, across all 18 myeloid clusters (Data S12). "
           "Referenced in Section 4.",
           "external_validation/scripts/06_origin_signature_scoring.R")

fig_heading(5, "TF mRNA vs. S100a9 expression, bulk RNA-seq (all 34 samples)")
add_figure(FIG, "14_tf_bulk_correlation.png", 9.5,
           "Scatter plots of each of 9 C/EBP- and AP-1-family TF genes' bulk expression against "
           "S100a9 expression, one panel per gene (Data S13). Referenced in Results 3.6.",
           "scripts/14_tf_activity_inference.R")

fig_heading(6, "C/EBP and AP-1 family TF mRNA dot plot by origin group, primary scRNA reference")
add_figure(FIG, "14_tf_scrna_dotplot.png", 7.5,
           "Dot plot of the 9-gene TF panel (Data S14) across the four refined origin groups. "
           "Referenced in Results 3.6.",
           "scripts/14_tf_activity_inference.R")

fig_heading(7, "S100A8hi_macrophage vs. Kupffer proportion over time, GSE156057")
add_figure(FIG, "15_fate_compositional_trend.png", 8,
           "Cell-class proportion vs. timepoint (12/24/36 weeks), by diet, for S100A8hi_macrophage "
           "and Kupffer (Data S16). Referenced in Results 3.6.",
           "scripts/15_fate_trajectory.R")

fig_heading(8, "Restricted UMAP of the four refined origin groups, primary scRNA reference")
add_figure(FIG, "15_fate_umap_origin.png", 6,
           "UMAP computed from only the four refined origin groups (S100A8hi_macrophage, "
           "Kupffer_resident, Macrophage_MoMF_LAM, Neutrophil), colored by group. Underlies the "
           "PCA-space nearest-neighbor analysis in Data S17. Referenced in Results 3.6, Section 4.",
           "scripts/15_fate_trajectory.R")

fig_heading(9, "Trem2/Gpnmb (LAM) module score on the restricted UMAP")
add_figure(FIG, "15_fate_umap_lamscore.png", 6,
           "Same UMAP embedding as Figure S8, colored by the Trem2/Gpnmb lipid-associated-macrophage "
           "module score, showing this signature concentrates in Macrophage_MoMF_LAM and is absent "
           "from S100A8hi_macrophage. Referenced in Results 3.1, Results 3.6.",
           "scripts/15_fate_trajectory.R")

# ---- Remaining pipeline QC/exploratory figures (primary reference), not otherwise embedded ----
fig_heading(10, "scRNA QC metrics before filtering, WT vs TG")
add_figure(FIG, "01_qc_violin_prefilter.png", 9,
           "Violin plots of nFeature_RNA, nCount_RNA and percent.mt per sample, before the QC filter "
           "described in Methods 2.2 (Data S18). Referenced in Methods 2.2.",
           "scripts/01_scRNA_qc.R")

fig_heading(11, "Full-resolution (28-cluster) UMAP, primary scRNA reference")
add_figure(FIG, "02_umap_clusters.png", 6,
           "UMAP of all quality-controlled cells at clustering resolution 0.8 (28 clusters), before "
           "collapsing to the 12 final cell types shown in Figure 1A (Data S19). Referenced in Methods 2.2.",
           "scripts/02_scRNA_cluster_annotate.R")

fig_heading(12, "28-cluster UMAP colored by genotype")
add_figure(FIG, "02_umap_by_genotype.png", 6,
           "Same UMAP as Figure S11, colored by genotype (WT vs TG) instead of cluster identity, showing "
           "no gross genotype-driven batch separation despite no batch correction being applied (Methods 2.2).",
           "scripts/02_scRNA_cluster_annotate.R")

fig_heading(13, "Canonical lineage marker dot plot, 28 clusters")
add_figure(FIG, "02_marker_dotplot.png", 10,
           "Dot plot of 22 canonical lineage marker genes (hepatocyte, Kupffer/macrophage, neutrophil, "
           "monocyte, LSEC, stellate, T/B/NK, cholangiocyte) across all 28 clusters -- the direct evidence "
           "used for the cluster-to-cell-type mapping in Methods 2.2 (Data S19). Referenced in Methods 2.2.",
           "scripts/02_scRNA_cluster_annotate.R")

fig_heading(14, "Final 12-cell-type UMAP, primary scRNA reference")
add_figure(FIG, "03_umap_celltype.png", 6.5,
           "UMAP colored by the final 12 annotated cell types (Methods 2.2), the source figure for "
           "Figure 1A. Referenced in Results 3.1.",
           "scripts/03_scRNA_annotate_finalize.R")

fig_heading(15, "S100A8hi_macrophage vs. Neutrophil vs. Macrophage_Kupffer marker check (exploratory version)")
add_figure(FIG, "03_confirm_s100a8_identity.png", 9,
           "Exploratory dot plot generated at the annotation-finalization stage (Methods 2.2), confirming "
           "S100A8hi_macrophage separates from Neutrophil and Macrophage_Kupffer before this exact panel "
           "was re-generated with final formatting as Figure 1B. Referenced in Results 3.1.",
           "scripts/03_scRNA_annotate_finalize.R")
doc.add_page_break()

fig_heading(16, "scRNA-observed cell-type composition, WT vs TG (ground truth)")
add_figure(FIG, "04_ground_truth_barplot.png", 8,
           "Bar chart of the ground-truth proportions in Data S21, all 12 cell types, WT vs TG. "
           "Referenced in Results 3.1/3.2, Section 4.",
           "scripts/04_scRNA_ground_truth_props.R")

fig_heading(17, "S100A8hi_macrophage deconvolution score, axis-1 (exploratory version)")
add_figure(FIG, "07_validation_S100A8_boxplot.png", 6,
           "Exploratory boxplot generated during the axis-1 validation analysis (Methods 2.5), showing the "
           "same S100A8hi_macrophage WT-vs-TG comparison later re-generated with Wilcoxon/Cohen's-d "
           "annotations as Figure 2B. Referenced in Results 3.2.",
           "scripts/07_validate_axis1.R")

fig_heading(18, "All 12 cell types, bulk deconvolution score, WT vs TG (axis-1, HFD)")
add_figure(FIG, "07_validation_all_celltypes.png", 9.5,
           "Boxplots of deconvolution score by genotype for all 12 cell types (not only "
           "Macrophage_Kupffer and S100A8hi_macrophage), axis-1 HFD cohort (Data S24). Referenced in "
           "Results 3.2.",
           "scripts/07_validate_axis1.R")
doc.add_page_break()

fig_heading(19, "S100A8hi_macrophage / Macrophage_Kupffer composition, WT vs MKO (exploratory version)")
add_figure(FIG, "08_MKO_key_celltypes.png", 7,
           "Exploratory boxplots generated during the axis-2 application analysis (Methods 2.6), the two "
           "cell types later re-generated with statistical annotations as Figure 3A-D. Referenced in "
           "Results 3.3.",
           "scripts/08_apply_axis2_MKO.R")

fig_heading(20, "All 12 cell types, WT vs MKO composition, Chow vs HFD")
add_figure(FIG, "08_MKO_all_celltypes.png", 9.5,
           "Boxplots of deconvolution score by genotype for all 12 cell types, both diets, axis-2 "
           "(Data S2/Data S10). Includes the Neutrophil and Mast_cell panels shown individually as "
           "Figure 3E-F. Referenced in Results 3.3.",
           "scripts/08_apply_axis2_MKO.R")
doc.add_page_break()

fig_heading(21, "S100A8hi_macrophage score vs. Cd36 expression, all HFD bulk samples (exploratory version)")
add_figure(FIG, "09_correlation_S100A8_vs_Cd36.png", 7,
           "Exploratory scatter plot generated during the lipid-gene correlation analysis (Methods 2.6), "
           "the S100A8hi_macrophage-vs-Cd36 relationship later re-generated with BH-q annotation as "
           "Figure 4B. Referenced in Results 3.4.",
           "scripts/09_correlate_lipid_genes.R")

fig_heading(22, "Four-panel analysis summary figure")
add_figure(FIG, "10_summary_figure.png", 9,
           "A single-page overview combining the scRNA reference UMAP, the axis-1 validation result, the "
           "axis-2 (MKO) null result, and the S100A8hi_macrophage-vs-Cd36 correlation -- assembled midway "
           "through the analysis as a working summary, distinct from (and predating) the four separate "
           "publication-formatted Figures 1-4. Referenced in Results 3.1-3.4 collectively.",
           "scripts/10_figures.R")
doc.add_page_break()

# ---- Remaining external-validation exploratory figures, not otherwise embedded ----
fig_heading(23, "GSE156057: full 40-cluster UMAP")
add_figure(EXT_FIG, "gse156057_umap_clusters.png", 6.5,
           "UMAP of all 40 clusters from the reclustered GSE156057 (CD45+-sorted) dataset (Methods 2.7), "
           "the source embedding for the cluster identification described in Results 3.5.",
           "external_validation/scripts/03_gse156057_qc_cluster.R")

fig_heading(24, "GSE156057: UMAP colored by sample (diet x timepoint)")
add_figure(EXT_FIG, "gse156057_umap_sample.png", 7,
           "Same UMAP as Figure S23, colored by the 6 individual samples (SD/WD x 12/24/36 weeks) instead "
           "of cluster identity.",
           "external_validation/scripts/03_gse156057_qc_cluster.R")

fig_heading(25, "GSE156057: full marker-panel dot plot, all 40 clusters")
add_figure(EXT_FIG, "gse156057_signature_dotplot.png", 10,
           "Dot plot of the same 17-gene marker panel as Data S4, across all 40 clusters (not only the 6 "
           "highlighted in Figure 5A). Referenced in Methods 2.7, Results 3.5.",
           "external_validation/scripts/03_gse156057_qc_cluster.R")
doc.add_page_break()

fig_heading(26, "GSE156057: all cell-class proportions by diet and timepoint")
add_figure(EXT_FIG, "gse156057_proportions.png", 9,
           "Proportion of S100A8hi_macrophage, Kupffer, Neutrophil and Other by diet and timepoint (Data "
           "S6/Data S16) -- Figure 5B shows only the S100A8hi_macrophage panel; this shows all four "
           "cell-class panels together. Referenced in Results 3.5, Results 3.6.",
           "external_validation/scripts/04_gse156057_proportions.R")

fig_heading(27, "GSE166504: full 18-cluster UMAP")
add_figure(EXT_FIG, "gse166504_umap_clusters.png", 6.5,
           "UMAP of all 18 myeloid subclusters from the reclustered GSE166504 dataset (Methods 2.7), the "
           "source embedding for Figure 5C and Data S7/S12/S26.",
           "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

fig_heading(28, "GSE166504: UMAP colored by the authors' original cell-type label")
add_figure(EXT_FIG, "gse166504_umap_authorlabel.png", 6.5,
           "Same UMAP as Figure S27, colored by the original authors' coarse CellType label (Kupffer "
           "cells / Monocyte-derived macrophage / Neutrophils) instead of this study's subclusters -- the "
           "source figure for the cross-tabulation in Data S8.",
           "external_validation/scripts/02_gse166504_cluster_annotate.R")

fig_heading(29, "GSE166504: UMAP colored by animal / condition")
add_figure(EXT_FIG, "gse166504_umap_animal.png", 9,
           "Same UMAP as Figure S27, faceted by condition (chow / 15-week NAFL / 30-week NASH / 34-week) "
           "and colored by individual animal, confirming no single-animal cluster dominates -- relevant "
           "given GSE166504's true biological replication (chow n=3, NAFL n=3, NASH n=4, 34wk n=1).",
           "external_validation/scripts/02_gse166504_cluster_annotate.R")
doc.add_page_break()

fig_heading(30, "GSE166504: full marker-panel dot plot, all 18 clusters")
add_figure(EXT_FIG, "gse166504_signature_dotplot.png", 9.5,
           "Dot plot of the same 12-gene marker panel as Data S7/S26, across all 18 myeloid subclusters. "
           "Referenced in Methods 2.7, Results 3.5.",
           "external_validation/scripts/02_gse166504_cluster_annotate.R")

print("Document complete.")
doc.save(OUT_PATH)
print(f"Saved to {OUT_PATH}")
